# This is a config for E2B sandbox template.
# You can use template ID (o7te0ovt3mepwlpibqie) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("o7te0ovt3mepwlpibqie") # Sync sandbox
# sandbox = await AsyncSandbox.create("o7te0ovt3mepwlpibqie") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('o7te0ovt3mepwlpibqie')

team_id = "1dcee919-3dcb-4817-8126-f58d9f39c0a4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_id = "o7te0ovt3mepwlpibqie"
