# This is a config for E2B sandbox template.
# You can use template ID (e7g1m4s4d011otjpqe9x) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("e7g1m4s4d011otjpqe9x") # Sync sandbox
# sandbox = await AsyncSandbox.create("e7g1m4s4d011otjpqe9x") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('e7g1m4s4d011otjpqe9x')

team_id = "1dcee919-3dcb-4817-8126-f58d9f39c0a4"
dockerfile = "e2b.Dockerfile"
template_id = "e7g1m4s4d011otjpqe9x"
